# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'LiveAudioRoom' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  plugin 'cocoapods-pod-sign'
  skip_pod_bundle_sign
  
  pod 'NEUIKit', :path => '../NEUIKit/NEUIKit.podspec'
  pod 'NEVoiceRoomUIKit', :path => '../NEVoiceRoomUIKit/NEVoiceRoomUIKit.podspec'
  pod 'NEOrderSong', :path => '../NEOrderSong/NEOrderSong.podspec'
  pod 'LottieSwift', :path => '../lottie/LottieSwift.podspec'
  pod 'NEVoiceRoomKit', :path => '../NEVoiceRoomKit/NEVoiceRoomKit.podspec'

  pod 'NERoomKit','1.12.2'
  pod 'NECopyrightedMedia','1.5.0'

  # Pods for NEVoiceRoomExample
  pod 'Masonry'
  pod 'NERtcSDK/Beauty', '4.6.43'
  pod 'NERtcSDK/FaceDetect', '4.6.43'
  pod 'NERtcSDK/Segment', '4.6.43'
  pod 'NERtcSDK/RtcBasic', '4.6.43'
  pod 'NIMSDK_LITE', '9.8.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
