# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'NEChatroom-iOS-ObjC' do

pod 'SVProgressHUD', '~> 2.2.5'
pod 'Reachability', '~> 3.1.1'
pod 'M80AttributedLabel', '~> 1.3.1'
pod 'YYWebImage', '~> 1.0.5'
pod 'MJRefresh', '~> 3.1.15.7'
pod 'NERtcSDK', '4.2.102'
pod 'NIMSDK_LITE', '8.2.0'
pod 'Masonry'
pod 'NELivePlayer', '2.7.0'
pod 'ReactiveObjC', '~> 3.1.0'
pod 'YYModel'
#pod 'lottie-ios', '~> 2.5.3'
pod 'YXAlog_iOS', '~> 0.1.0'

end

