# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LiveAudioRoom' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  use_frameworks!
#  plugin 'cocoapods-pod-sign'
#  skip_pod_bundle_sign
  
  def imVersion
    '9.12.0'
  end

  def rtcVersion
    '5.4.0'
  end

  #公共库(被多余一个组件引用，可定义多个)
  def imSDKPod
    pod 'NIMSDK_LITE',imVersion
  end

  def rtcBasicPod
    pod 'NERtcSDK/RtcBasic',rtcVersion
  end

def thirdPartyLibraryPod
  pod 'SDWebImage', '5.7.1'
  pod 'AFNetworking', '4.0'
  pod 'Masonry'
  pod 'Toast'
end

  imSDKPod
  rtcBasicPod
  thirdPartyLibraryPod
  
#源码依赖
  pod 'NEUIKit', :path => '../NEUIKit/NEUIKit.podspec'
  pod 'NEVoiceRoomKit', :path => '../NEVoiceRoomKit/NEVoiceRoomKit.podspec'
  pod 'NEVoiceRoomUIKit', :path => '../NEVoiceRoomUIKit/NEVoiceRoomUIKit.podspec'
pod 'NEOrderSong', :path => '../NEOrderSong/NEOrderSong.podspec'
pod 'LottieSwift', :path => '../lottie/LottieSwift.podspec'
pod 'NESocialUIKit', :path => '../NESocialUIKit/NESocialUIKit.podspec'

#登录
pod 'NELoginSample',:path => '../NELoginSample/NELoginSample.podspec'

#远端依赖
pod 'NERoomKit/Special_All', '1.18.0'
pod 'NECopyrightedMedia', '1.7.0'
pod 'NEAudioEffectKit', '1.4.0'
pod 'NECommonKit','9.6.0'
pod 'IHProgressHUD'
  




end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
